// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class MeRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.MeRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.MeRsp";
    }

    public com.duowan.gamenews.User user = null;

    public int favCount = 0;

    public com.duowan.gamenews.User getUser()
    {
        return user;
    }

    public void  setUser(com.duowan.gamenews.User user)
    {
        this.user = user;
    }

    public int getFavCount()
    {
        return favCount;
    }

    public void  setFavCount(int favCount)
    {
        this.favCount = favCount;
    }

    public MeRsp()
    {
        setUser(user);
        setFavCount(favCount);
    }

    public MeRsp(com.duowan.gamenews.User user, int favCount)
    {
        setUser(user);
        setFavCount(favCount);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        MeRsp t = (MeRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(user, t.user) && 
            com.duowan.taf.jce.JceUtil.equals(favCount, t.favCount) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != user)
        {
            _os.write(user, 0);
        }
        _os.write(favCount, 1);
    }

    static com.duowan.gamenews.User cache_user;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_user)
        {
            cache_user = new com.duowan.gamenews.User();
        }
        setUser((com.duowan.gamenews.User) _is.read(cache_user, 0, false));

        setFavCount((int) _is.read(favCount, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(user, "user");
        _ds.display(favCount, "favCount");
    }

}

