// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class ArticleFlag
{
    private static ArticleFlag[] __values = new ArticleFlag[5];
    private int __value;
    private String __T = new String();

    public static final int _ARTICLE_FLAG_BIGIMAGE = 1;
    public static final ArticleFlag ARTICLE_FLAG_BIGIMAGE = new ArticleFlag(0,_ARTICLE_FLAG_BIGIMAGE,"ARTICLE_FLAG_BIGIMAGE");
    public static final int _ARTICLE_FLAG_TOP = 2;
    public static final ArticleFlag ARTICLE_FLAG_TOP = new ArticleFlag(1,_ARTICLE_FLAG_TOP,"ARTICLE_FLAG_TOP");
    public static final int _ARTICLE_FLAG_RECOMM = 4;
    public static final ArticleFlag ARTICLE_FLAG_RECOMM = new ArticleFlag(2,_ARTICLE_FLAG_RECOMM,"ARTICLE_FLAG_RECOMM");
    public static final int _ARTICLE_FLAG_HOT = 8;
    public static final ArticleFlag ARTICLE_FLAG_HOT = new ArticleFlag(3,_ARTICLE_FLAG_HOT,"ARTICLE_FLAG_HOT");
    public static final int _ARTICLE_FLAG_ADV = 16;
    public static final ArticleFlag ARTICLE_FLAG_ADV = new ArticleFlag(4,_ARTICLE_FLAG_ADV,"ARTICLE_FLAG_ADV");

    public static ArticleFlag convert(int val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].value() == val)
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public static ArticleFlag convert(String val)
    {
        for(int __i = 0; __i < __values.length; ++__i)
        {
            if(__values[__i].toString().equals(val))
            {
                return __values[__i];
            }
        }
        assert false;
        return null;
    }

    public int value()
    {
        return __value;
    }

    public String toString()
    {
        return __T;
    }

    private ArticleFlag(int index, int val, String s)
    {
        __T = s;
        __value = val;
        __values[index] = this;
    }

}
