// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class AppInitRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.AppInitRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.AppInitRsp";
    }

    public java.util.Map<String, java.util.ArrayList<String>> suggestionList = null;

    public java.util.ArrayList<com.duowan.gamenews.Channel> recommendList = null;

    public java.util.ArrayList<com.duowan.gamenews.Channel> activeList = null;

    public java.util.Map<String, java.util.ArrayList<String>> getSuggestionList()
    {
        return suggestionList;
    }

    public void  setSuggestionList(java.util.Map<String, java.util.ArrayList<String>> suggestionList)
    {
        this.suggestionList = suggestionList;
    }

    public java.util.ArrayList<com.duowan.gamenews.Channel> getRecommendList()
    {
        return recommendList;
    }

    public void  setRecommendList(java.util.ArrayList<com.duowan.gamenews.Channel> recommendList)
    {
        this.recommendList = recommendList;
    }

    public java.util.ArrayList<com.duowan.gamenews.Channel> getActiveList()
    {
        return activeList;
    }

    public void  setActiveList(java.util.ArrayList<com.duowan.gamenews.Channel> activeList)
    {
        this.activeList = activeList;
    }

    public AppInitRsp()
    {
        setSuggestionList(suggestionList);
        setRecommendList(recommendList);
        setActiveList(activeList);
    }

    public AppInitRsp(java.util.Map<String, java.util.ArrayList<String>> suggestionList, java.util.ArrayList<com.duowan.gamenews.Channel> recommendList, java.util.ArrayList<com.duowan.gamenews.Channel> activeList)
    {
        setSuggestionList(suggestionList);
        setRecommendList(recommendList);
        setActiveList(activeList);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppInitRsp t = (AppInitRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(suggestionList, t.suggestionList) && 
            com.duowan.taf.jce.JceUtil.equals(recommendList, t.recommendList) && 
            com.duowan.taf.jce.JceUtil.equals(activeList, t.activeList) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != suggestionList)
        {
            _os.write(suggestionList, 0);
        }
        if (null != recommendList)
        {
            _os.write(recommendList, 1);
        }
        if (null != activeList)
        {
            _os.write(activeList, 2);
        }
    }

    static java.util.Map<String, java.util.ArrayList<String>> cache_suggestionList;
    static java.util.ArrayList<com.duowan.gamenews.Channel> cache_recommendList;
    static java.util.ArrayList<com.duowan.gamenews.Channel> cache_activeList;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_suggestionList)
        {
            cache_suggestionList = new java.util.HashMap<String, java.util.ArrayList<String>>();
            String __var_41 = "";
            java.util.ArrayList<String> __var_42 = new java.util.ArrayList<String>();
            String __var_43 = "";
            ((java.util.ArrayList<String>)__var_42).add(__var_43);
            cache_suggestionList.put(__var_41, __var_42);
        }
        setSuggestionList((java.util.Map<String, java.util.ArrayList<String>>) _is.read(cache_suggestionList, 0, false));

        if(null == cache_recommendList)
        {
            cache_recommendList = new java.util.ArrayList<com.duowan.gamenews.Channel>();
            com.duowan.gamenews.Channel __var_44 = new com.duowan.gamenews.Channel();
            ((java.util.ArrayList<com.duowan.gamenews.Channel>)cache_recommendList).add(__var_44);
        }
        setRecommendList((java.util.ArrayList<com.duowan.gamenews.Channel>) _is.read(cache_recommendList, 1, false));

        if(null == cache_activeList)
        {
            cache_activeList = new java.util.ArrayList<com.duowan.gamenews.Channel>();
            com.duowan.gamenews.Channel __var_45 = new com.duowan.gamenews.Channel();
            ((java.util.ArrayList<com.duowan.gamenews.Channel>)cache_activeList).add(__var_45);
        }
        setActiveList((java.util.ArrayList<com.duowan.gamenews.Channel>) _is.read(cache_activeList, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(suggestionList, "suggestionList");
        _ds.display(recommendList, "recommendList");
        _ds.display(activeList, "activeList");
    }

}

