// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class GetChannelArticleListRsp extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.GetChannelArticleListRsp";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.GetChannelArticleListRsp";
    }

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList = null;

    public java.util.Map<Integer, String> attachInfo = null;

    public boolean hasMore = true;

    public java.util.ArrayList<com.duowan.gamenews.ArticleInfo> getArticleList()
    {
        return articleList;
    }

    public void  setArticleList(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList)
    {
        this.articleList = articleList;
    }

    public java.util.Map<Integer, String> getAttachInfo()
    {
        return attachInfo;
    }

    public void  setAttachInfo(java.util.Map<Integer, String> attachInfo)
    {
        this.attachInfo = attachInfo;
    }

    public boolean getHasMore()
    {
        return hasMore;
    }

    public void  setHasMore(boolean hasMore)
    {
        this.hasMore = hasMore;
    }

    public GetChannelArticleListRsp()
    {
        setArticleList(articleList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public GetChannelArticleListRsp(java.util.ArrayList<com.duowan.gamenews.ArticleInfo> articleList, java.util.Map<Integer, String> attachInfo, boolean hasMore)
    {
        setArticleList(articleList);
        setAttachInfo(attachInfo);
        setHasMore(hasMore);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        GetChannelArticleListRsp t = (GetChannelArticleListRsp) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(articleList, t.articleList) && 
            com.duowan.taf.jce.JceUtil.equals(attachInfo, t.attachInfo) && 
            com.duowan.taf.jce.JceUtil.equals(hasMore, t.hasMore) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != articleList)
        {
            _os.write(articleList, 0);
        }
        if (null != attachInfo)
        {
            _os.write(attachInfo, 1);
        }
        _os.write(hasMore, 2);
    }

    static java.util.ArrayList<com.duowan.gamenews.ArticleInfo> cache_articleList;
    static java.util.Map<Integer, String> cache_attachInfo;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_articleList)
        {
            cache_articleList = new java.util.ArrayList<com.duowan.gamenews.ArticleInfo>();
            com.duowan.gamenews.ArticleInfo __var_27 = new com.duowan.gamenews.ArticleInfo();
            ((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>)cache_articleList).add(__var_27);
        }
        setArticleList((java.util.ArrayList<com.duowan.gamenews.ArticleInfo>) _is.read(cache_articleList, 0, false));

        if(null == cache_attachInfo)
        {
            cache_attachInfo = new java.util.HashMap<Integer, String>();
            Integer __var_28 = 0;
            String __var_29 = "";
            cache_attachInfo.put(__var_28, __var_29);
        }
        setAttachInfo((java.util.Map<Integer, String>) _is.read(cache_attachInfo, 1, false));

        setHasMore((boolean) _is.read(hasMore, 2, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(articleList, "articleList");
        _ds.display(attachInfo, "attachInfo");
        _ds.display(hasMore, "hasMore");
    }

}

