// **********************************************************************
// This file was generated by a TAF parser!
// TAF version 2.1.4.3.
// Generated from `gamenews.jce'
// **********************************************************************

package com.duowan.gamenews;

public final class AppInitReq extends com.duowan.taf.jce.JceStruct implements java.lang.Cloneable
{
    public String className()
    {
        return "gamenews.AppInitReq";
    }

    public String fullClassName()
    {
        return "com.duowan.gamenews.AppInitReq";
    }

    public java.util.ArrayList<String> gameName = null;

    public int serviceType = 0;

    public java.util.ArrayList<String> getGameName()
    {
        return gameName;
    }

    public void  setGameName(java.util.ArrayList<String> gameName)
    {
        this.gameName = gameName;
    }

    public int getServiceType()
    {
        return serviceType;
    }

    public void  setServiceType(int serviceType)
    {
        this.serviceType = serviceType;
    }

    public AppInitReq()
    {
        setGameName(gameName);
        setServiceType(serviceType);
    }

    public AppInitReq(java.util.ArrayList<String> gameName, int serviceType)
    {
        setGameName(gameName);
        setServiceType(serviceType);
    }

    public boolean equals(Object o)
    {
        if(o == null)
        {
            return false;
        }

        AppInitReq t = (AppInitReq) o;
        return (
            com.duowan.taf.jce.JceUtil.equals(gameName, t.gameName) && 
            com.duowan.taf.jce.JceUtil.equals(serviceType, t.serviceType) );
    }

    public int hashCode()
    {
        try
        {
            throw new Exception("Need define key first!");
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return 0;
    }
    public java.lang.Object clone()
    {
        java.lang.Object o = null;
        try
        {
            o = super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return o;
    }

    public void writeTo(com.duowan.taf.jce.JceOutputStream _os)
    {
        if (null != gameName)
        {
            _os.write(gameName, 0);
        }
        _os.write(serviceType, 1);
    }

    static java.util.ArrayList<String> cache_gameName;

    public void readFrom(com.duowan.taf.jce.JceInputStream _is)
    {
        if(null == cache_gameName)
        {
            cache_gameName = new java.util.ArrayList<String>();
            String __var_40 = "";
            ((java.util.ArrayList<String>)cache_gameName).add(__var_40);
        }
        setGameName((java.util.ArrayList<String>) _is.read(cache_gameName, 0, false));

        setServiceType((int) _is.read(serviceType, 1, false));

    }

    public void display(java.lang.StringBuilder _os, int _level)
    {
        com.duowan.taf.jce.JceDisplayer _ds = new com.duowan.taf.jce.JceDisplayer(_os, _level);
        _ds.display(gameName, "gameName");
        _ds.display(serviceType, "serviceType");
    }

}

